import Head from "next/head";
import Image from "next/image";
import { Box, Flex } from "@chakra-ui/react";
import TopAppBar from "../components/TopAppBar";
import Map from "../components/Map";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>1 Up Health</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap" rel="stylesheet" />
      </Head>
      <Flex flexDirection="column" h="100vh">
        <TopAppBar />

        <Box flex={1}>
          <Map />
        </Box>
      </Flex>
    </Box>
  );
}
